[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin open-git-remote"
desc = "open git remote url"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd to the git root"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["f", "c"]
run = ["plugin copy-file-contents"]
desc = "Copy File Contents"

[[mgr.prepend_keymap]]
on = ["f", "y"]
run = ["plugin clippy"]
desc = "Copy File"

[[manager.prepend_keymap]]
on = ["f", "p"]
run = "plugin path-from-root"
desc = "Copy File Path from git root"

[[mgr.prepend_keymap]]
on = ["y"]
run = ["yank", "plugin clippy"]
desc = "Yank and copy file with Clippy"

[[mgr.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["yank", 'plugin clipboard -- --action=copy']
desc = "Copy the hovered file or directory"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = ['plugin clipboard -- --action=paste']
desc = "Paste the path into the command line"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# If you also using Yazi on Windows:
[[mgr.prepend_keymap]]
on = "!"
for = "windows"
run = 'shell "powershell.exe" --block'
desc = "Open PowerShell here"

[[plugin.prepend_previewers]]
url = "*.md"
run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dracula -- "$1"'

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.append_previewers]]
url = "*"
run = 'piper -- hexyl --border=none --terminal-width=$w "$1"'

